apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: upcloudnodeclasses.karpenter.k8s.upcloud
spec:
  group: karpenter.k8s.upcloud
  names:
    kind: UpCloudNodeClass
    listKind: UpCloudNodeClassList
    plural: upcloudnodeclasses
    singular: upcloudnodeclass
  scope: Cluster
  versions:
    - name: v1alpha2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                zone:
                  type: string
                plan:
                  type: string
                storage:
                  type: object
                  properties:
                    size:
                      type: integer
                      minimum: 10
                    tier:
                      type: string
                      enum: [maxiops, standard, hdd]
                    encrypted:
                      type: boolean
                sshKeys:
                  type: array
                  items:
                    type: string
                kubeletArgs:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                labels:
                  type: object
                  additionalProperties:
                    type: string
                taints:
                  type: array
                  items:
                    type: object
                    properties:
                      effect:
                        type: string
                      key:
                        type: string
                      value:
                        type: string
                antiAffinity:
                  type: boolean
                utilityNetworkAccess:
                  type: boolean
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
