apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karpenter-upcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-upcloud.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "karpenter-upcloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "karpenter-upcloud.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}{{ tpl (toYaml .) $ | nindent 8 }}{{ end }}
      annotations:
        {{- with .Values.podAnnotations }}{{ tpl (toYaml .) $ | nindent 8 }}{{ end }}
    spec:
      serviceAccountName: {{ include "karpenter-upcloud.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: karpenter
          image: {{ include "karpenter-upcloud.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: http-health
              containerPort: 8081
              protocol: TCP
          env:
            - name: UPCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "karpenter-upcloud.secretName" . }}
                  key: {{ .Values.config.auth.tokenKey }}
            - name: UPCLOUD_KUBERNETES_CLUSTER_ID
              value: {{ required "config.clusterUUID is required" .Values.config.clusterUUID }}
            {{- if .Values.config.templateUUID }}
            - name: UPCLOUD_TEMPLATE_UUID
              value: {{ .Values.config.templateUUID }}
            {{- end }}
            {{- if .Values.config.nodeclaimTTL.enabled }}
            - name: UPCLOUD_NODECLAIM_TTL
              value: {{ .Values.config.nodeclaimTTL.ttl | quote }}
            {{- end }}
            - name: UPCLOUD_REPAIR_TOLERATION
              value: {{ .Values.config.repairToleration | quote }}
            {{- with .Values.extraEnv }}{{ tpl (toYaml .) $ | nindent 12 }}{{ end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
