{{- with .Values.nodeClass }}
{{- if .enabled }}
apiVersion: karpenter.k8s.upcloud/v1alpha2
kind: UpCloudNodeClass
metadata:
  name: {{ .name | quote }}
  labels:
    {{- include "karpenter-upcloud.labels" $ | nindent 4 }}
spec:
  zone: {{ required "nodeClass.zone is required when nodeClass.enabled=true" .zone | quote }}
  plan: {{ .plan | quote }}
  templateUUID: {{ $.Values.config.templateUUID | quote }}
  {{- if .storage }}
  storage:
    {{- if .storage.size }}
    size: {{ .storage.size }}
    {{- end }}
    {{- if .storage.tier }}
    tier: {{ .storage.tier | quote }}
    {{- end }}
    {{- if hasKey .storage "encrypted" }}
    encrypted: {{ .storage.encrypted }}
    {{- end }}
  {{- end }}
  {{- if .serverGroupUUID }}
  serverGroupUUID: {{ .serverGroupUUID | quote }}
  {{- end }}
{{- end }}
{{- end }}
