{{- if and (not .Values.config.auth.existingSecret) .Values.config.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-upcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-upcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.auth.tokenKey | default "token" }}: {{ .Values.config.auth.token }}
{{- end }}
