version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      kubernetes:
        patterns:
          - k8s.io/*

  - package-ecosystem: "github-actions"
    commit-message:
      prefix: chore(actions)
    directory: "/"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
