apiVersion: v2
name: karpenter-upcloud
description: Karpenter provider for UpCloud
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - karpenter
  - upcloud
  - autoscaling
home: https://github.com/upcloud-tools/karpenter-provider-upcloud
sources:
  - https://github.com/upcloud-tools/karpenter-provider-upcloud
