apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.upcloud.com
        kind: UpCloudNodeClass
        name: default
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values:
            - "CLOUDNATIVE-2xCPU-4GB"
            - "CLOUDNATIVE-4xCPU-8GB"
      expireAfter: 720h
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 50m
