apiVersion: karpenter.upcloud.com/v1alpha1
kind: UpCloudNodeClass
metadata:
  name: default
spec:
  zone: de-fra1
  plan: CLOUDNATIVE-2xCPU-4GB
  # Optional: root disk configuration.
  storage:
    size: 20          # default 20 (GB)
    tier: standard    # standard|maxiops|hdd, default standard
    encrypted: false  # optional, enables encryption at rest, default false
