{{- if and (not .Values.existingSecret) .Values.credentials.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-upcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-upcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.credentials.token }}
{{- end }}
