apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "karpenter-upcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-upcloud.labels" . | nindent 4 }}
