ARG GO_VERSION=1.26.5

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION} AS build
ARG VERSION
ARG COMMIT
ARG TREE_STATE
ARG TARGETOS
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -ldflags="-s -w -X github.com/upcloud-tools/karpenter-provider-upcloud/internal/version.Version=${VERSION} -X github.com/upcloud-tools/karpenter-provider-upcloud/internal/version.Commit=${COMMIT} -X github.com/upcloud-tools/karpenter-provider-upcloud/internal/version.TreeState=${TREE_STATE}" \
    -o karpenter-upcloud ./cmd/karpenter-upcloud

FROM alpine:3.23.5

LABEL org.opencontainers.image.source=https://github.com/upcloud-tools/karpenter-provider-upcloud \
      org.opencontainers.image.description="Karpenter provider for UpCloud Kubernetes Service"

RUN apk add --no-cache ca-certificates

COPY --from=build /workspace/karpenter-upcloud /bin/

ENTRYPOINT ["/bin/karpenter-upcloud"]
