name: Dependency Review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: upcloud-tools/gha-actions/.github/workflows/dependency-review.yaml@f2881d6a065803a93a5af104f83413f4b6f31ca0 # main
    secrets: inherit
