name: Dependency Review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: upcloud-tools/gha-actions/.github/workflows/dependency-review.yaml@6666b24558f9c6f4acbf12f5e186b81351f20ffb
    secrets: inherit
