name: E2E tests

on:
  workflow_dispatch:
    inputs:
      nodeclaimttl-tests:
        type: choice
        description: Run node claim TTL tests
        default: 'no'
        options:
          - 'yes'
          - 'no'

env:
  GO_VERSION: '1.26.5'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - capacityType: on-demand
            plan: CLOUDNATIVE-2xCPU-4GB
          - capacityType: spot
            # Since spot capacity can be limited, we will try up to 3 plans
            plan: GPU-SPOT-8xCPU-64GB-1xL4
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Live provisioning e2e (${{ matrix.capacityType }})
        env:
          UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
          UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.UPCLOUD_KUBERNETES_CLUSTER_ID }}
          UPCLOUD_E2E_PROVISION: "1"
          UPCLOUD_E2E_PLAN: ${{ matrix.plan }}
          UPCLOUD_E2E_CAPACITY_TYPE: ${{ matrix.capacityType }}
        run: go test -tags e2e ./test/e2e/ -run TestLiveCloudProviderCreate -v -timeout 20m

      - name: Node claim TTL e2e (${{ matrix.capacityType }})
        if: ${{ github.event.inputs.nodeclaimttl-tests == 'yes' }}
        env:
          UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
          UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.UPCLOUD_KUBERNETES_CLUSTER_ID }}
          UPCLOUD_E2E_PROVISION: "1"
          UPCLOUD_E2E_PLAN: ${{ matrix.plan }}
          UPCLOUD_E2E_CAPACITY_TYPE: ${{ matrix.capacityType }}
        run: go test -tags e2e ./test/e2e/ -run TestLiveNodeClaimTTL -v -timeout 20m
