name: E2E tests

on:
  workflow_dispatch:
    inputs:
      nodeclaimttl-tests:
        type: choice
        description: Run node claim TTL tests
        default: 'no'
        options:
          - 'yes'
          - 'no'
      image_tag:
        type: string
        description: Image tag to test (default latest)
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  provisioning:
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit

  nodeclaimttl:
    if: ${{ github.event.inputs.nodeclaimttl-tests == 'yes' }}
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      e2e_test: TestLiveNodeClaimTTL
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
