name: Test E2E

on:
  workflow_dispatch:
    inputs:
      nodeclaimttl-tests:
        type: choice
        description: Run node claim TTL tests
        default: 'no'
        options:
          - 'yes'
          - 'no'
      image_tag:
        type: string
        description: Image tag to test (default latest)
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read

jobs:
  e2e:
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      run_ttl: ${{ inputs.nodeclaimttl-tests == 'yes' }}
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
