name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - '.github/workflows/test.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - '.github/workflows/test.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: upcloud-tools/gha-actions/.github/workflows/test-go.yaml@f2881d6a065803a93a5af104f83413f4b6f31ca0 # main
